services:
  # defines all containers/services for the app

  backend:
    # FastAPI backend service

    build: .
    # builds Docker image using Dockerfile in current folder

    ports:
      - "8000:8000"
      # maps your computer's port 8000 to container port 8000

    env_file:
      - .env
      # loads environment variables from your .env file

    depends_on:
      - db
      # starts database container before backend container


  db:
    # PostgreSQL database service

    image: postgres:16
    # uses official PostgreSQL version 16 Docker image

    environment:
      POSTGRES_USER: postgres
      # database username

      POSTGRES_PASSWORD: postgres
      # database password for local Docker development

      POSTGRES_DB: echelon
      # database name

    ports:
      - "5432:5432"
      # maps local PostgreSQL port to container PostgreSQL port

    volumes:
      - postgres_data:/var/lib/postgresql/data
      # keeps database data even if container stops


volumes:
  postgres_data:
  # named Docker volume for persistent PostgreSQL storage